name: Run deploy.sh on dev branch

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci

      - name: Add .env file
        run: |
          touch .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "ACCESS_SECRET_KEY=${{ secrets.ACCESS_SECRET_KEY }}" >> .env
          echo "REFRESH_SECRET_KEY=${{ secrets.REFRESH_SECRET_KEY }}" >> .env
          echo "EMAIL_CRYPT_SECRET_KEY=${{ secrets.EMAIL_CRYPT_SECRET_KEY }}" >> .env
          echo "EMAIL_CRYPT_ALGORITHM=${{ secrets.EMAIL_CRYPT_ALGORITHM }}" >> .env
          echo "AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" >> .env
          echo "AWS_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }}" >> .env
          echo "AWS_S3_BUCKET_REGION=${{ secrets.AWS_S3_BUCKET_REGION }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env
          echo "APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }}" >> .env
          echo "APPLE_KEY_TEAM_ID=${{ secrets.APPLE_KEY_TEAM_ID }}" >> .env
          echo "APPLE_KEY_CLIENT_ID=${{ secrets.APPLE_KEY_CLIENT_ID }}" >> .env
          echo "APPLE_KEY_ALGORITHM=${{ secrets.APPLE_KEY_ALGORITHM }}" >> .env

      - name: Add EC2 KEY
        run: |
          touch scripts/mappilogue-ec2-key.pem
          echo "${{ secrets.MAPPILOGUE_EC2_KEY_PEM }}" >> scripts/mappilogue-ec2-key.pem

      - name: Add Apple Social Login Key
        run: |
          touch apple-social-login-key.p8
          echo "${{ secrets.APPLE_SOCIAL_LOGIN_KEY }}" >> apple-social-login-key.p8

      - name: Add SSH key to known_hosts
        run: ssh-keyscan -H ${{ secrets.REDIS_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy-dev.sh
        run: npm run deploy:dev
