name: Run deploy.sh on dev branch

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest # 실행할 환경

    steps:
      - uses: actions/checkout@v2 # 레포지토리 체크아웃

      # - name: Set up Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '20' # 원하는 Node.js 버전

      # - name: Install Dependencies
      #   run: npm install

      - name: Run deploy.sh
        run: npm run deploy
