name: Docker Image CI

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build -t Mappilogue-Server .
      - name: taging
        run: docker tag Mappilogue-Server:latest iamkanguk97/Mappilogue-Server:latest
      - name: Push to Dockerhub
        run: docker push iamkanguk97/Mappilogue-Server:latest
